services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: transcendence_app:latest
    ports:
      - "8443:8443"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - server_database:/app/server/database
      - ./server/.env:/app/server/.env:ro
    depends_on:
      - redis

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  server_database:
  redis_data:
