export const gameProperties = {
GAME_WIDTH : 8,
GAME_HEIGHT : 4,
PADDLE_WIDTH : 0.1,
PADDLE_HEIGHT : 0.8,
BALL_SIZE : 0.4,
BALL_SPEED_Z : 3,
BALL_SPEED_X : 2,
PADDLE_SPEED : 4,
BALL_COUNT : 3,
WINNING_SCORE : 5
}

/* TABLE_WIDTH: 4,
  TABLE_DEPTH: 8,
  PADDLE_WIDTH: 0.8,
  PADDLE_HEIGHT: 0.6,
  PADDLE_DEPTH: 0.1,
  PADDLE_SPEED: 2,
  BALL_RADIUS: 0.2,
  BALL_SPEED: 1.5, */