export const gameProperties = {
GAME_WIDTH : 8,
GAME_HEIGHT : 4,
EXTRA_SPACE: 0.5,
PADDLE_WIDTH : 0.1,
PADDLE_HEIGHT : 0.8,
BALL_SIZE : 0.4,
BALL_RADIUS : 0.2,
BALL_SPEED_Z : 0.5,
BALL_SPEED_X : 0.3,
PADDLE_SPEED : 0.1,
DELTA_SPEED : 8,
BALL_COUNT : 3,
WINNING_SCORE : 5,
}
export const PAD_MAX_POS_X = (gameProperties.GAME_HEIGHT - gameProperties.PADDLE_HEIGHT) / 2

/* 
  TABLE_WIDTH: 4,
  TABLE_DEPTH: 8,
  WATER_EXTRA_SPACE: 1,
  PADDLE_WIDTH: 0.8,
  PADDLE_HEIGHT: 0.6,
  PADDLE_DEPTH: 0.1,
  PADDLE_SPEED: 2,
  BALL_RADIUS: 0.2,
  BALL_SPEED: 1.5,
  */