export const GAME_CONSTANTS = {
  TABLE_WIDTH: 4,
  TABLE_DEPTH: 8,
  PADDLE_WIDTH: 0.8,
  PADDLE_HEIGHT: 0.6,
  PADDLE_DEPTH: 0.1,
  PADDLE_SPEED: 0.1,
  BALL_RADIUS: 0.2,
  BALL_SPEED: 0.15,
  WATER_LEVEL: 0,
  FLOOR_LEVEL: -2,
  WATER_EXTRA_SPACE: 1,
  WALL_THICKNESS: 0.2,
  WALL_HEIGHT: 2.5
};
